# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abcaf3ee6e0a97973e0e33cf00d66185c2f49e66f8c6419c706560e4ee84da27a266e473279b5ab5766d1afbb19879f2e4f7707c4e41a099ff6ba06c4d255565

test:
  secret_key_base: 8adf15894ed744591c45453dba74c2e7529b77600bfc1e20034eaf2c3c50df678122f4f456861e7868c235f324c260a9a1cf5230372b51888ac321212f5ab7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
